# Generated by Django 5.2.8 on 2025-11-23 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0010_alter_room_dormitory'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='main_ip',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
