# Generated by Django 5.2.8 on 2025-11-23 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0011_device_main_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='main_ip',
        ),
    ]
